### ISSUE TITLE
Angular v14 Peer Dependencies

### ISSUE THREAD

**Issue by dgonzo27** [jadengis/ng-helmet#5]
Hi @jadengis,

Looks like I can't install this library in my Angular v14.1.0 application due to some peer dependencies.  I know you pinned these dependencies to range from `>=13.0.0` and `<15.0.0` but npm is still throwing a fit.  Could you please take a look?

![Screen Shot 2022-08-14 at 8 13 04 PM](https://user-images.githubusercontent.com/53017996/184562492-330b85f6-696f-4d36-9c54-2b641411c3f4.png)

**Comment by jadengis** [comment]
Hey @dgonzo27 thanks for the bug report! Looks like `@angular/platform-browser-dynamic` got pulled in as a dependency even though its not being used. Let me fix this and I can push a new version.

**Comment by jadengis** [comment]
Hey @dgonzo27, I've published v2.0.1 which shouldn't have the issue you were experiencing above. Let me know if it works for you. Thanks!
